### Basics of NumPy Arrays

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays. In some ways, NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python. Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array.

![numpy_arrays](images/npArray.png)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # 1D array
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) # 2D array
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]]) # 3D array

In [3]:
# Array dimensions

a.shape

(3,)

In [4]:
b.shape

(2, 3)

In [5]:
c.shape

(2, 2, 3)

In [6]:
len(a) # Length of array

3

In [7]:
len(b), len(c)

(2, 2)

In [8]:
# Number of array dimensions

a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [9]:
# Number of array elements

a.size, b.size, c.size

(3, 6, 12)

In [10]:
# Data type of array elements

a.dtype, b.dtype, c.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [11]:
#Convert an array to a different type

b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

#### Data Types

**np.int64** : Signed 64-bit integer types<br>
**np.float32** : Standard double-precision floating point<br>
**np.complex** : Complex numbers represented by 128 floats<br>
**np.bool** : Boolean type storing TRUE and FALSE values<br>
**np.object** : Python object type<br>
**np.string_** : Fixed-length string type<br>
**np.unicode_** : Fixed-length unicode type

In [12]:
np.zeros((3)) # Create an array of zeros

array([0., 0., 0.])

In [13]:
np.ones((2,3)) # Create an array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.arange(10,25,5) # Create an array of evenly spaced values (step value)

array([10, 15, 20])

In [15]:
np.arange(0,1,.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [16]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
#Create an array with random values

In [18]:
np.random.randint(10, size = 6)
#np.random.randint(low = 1,high = 100, size = (2,4))

array([4, 5, 2, 8, 4, 2])

In [19]:
np.random.random((2,2)) #To generate random numbers of desired size between zero and 1 only

array([[0.73947526, 0.44849167],
       [0.26271053, 0.09889541]])

In [20]:
#np.random.random((2,2))*100

In [32]:
np.random.seed(0)  #Seed for reproducibility
np.random.randint(10, size = 6)

array([5, 0, 3, 3, 7, 9])

#### Aggregate Functions

In [22]:
a.sum() #Array-wise sum

6

In [23]:
b.sum()

21.5

In [24]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [25]:
b.sum(axis = 0)

array([5.5, 7. , 9. ])

In [26]:
a.min() #Array-wise minimum value

1

In [27]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [28]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [29]:
b.mean()

3.5833333333333335

In [30]:
np.median(b)

3.5